### ISSUE TITLE
Nur einen Server starten.

### ISSUE THREAD

**Issue by kisshering** [Kyri123/ArkLin2.0#7]
Hab leider noch ein Riesen Problem gefunden. Man kann nur einen Ark Server starten. Möchte man nen zweiten starten, springt dieser sofort wieder auf offline. Ist egal welchen Server man nimmt. Es kann immer nur einer online sein.

**Comment by Kyri123** [comment]
Da du mir ja zugriff erteilt hast: du benutzt auf beiden server den gleichen port. was das auslöst.
![image](https://user-images.githubusercontent.com/26281855/234473726-d51be2a5-806d-444b-bc72-4846f0aeea8e.png)
![image](https://user-images.githubusercontent.com/26281855/234473783-c85cd44d-471c-4198-956c-f47e04b1bff6.png)
